/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
            'alice, serif': '<script src=\"http://use.edgefonts.net/alice:n4:all.js\"></script>'        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'fond_espace3',
                            type: 'image',
                            rect: ['0px', '0px', '1024px', '768px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"fond_espace3.png",'0px','0px']
                        },
                        {
                            id: 'bucheron',
                            type: 'image',
                            rect: ['-46px', '486px', '305px', '320px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"bucheron.png",'0px','0px'],
                            transform: [[],['1']]
                        },
                        {
                            id: 'Chris_Zabriskie_-_09_-_Cylinder_Nine2',
                            display: 'none',
                            type: 'audio',
                            tag: 'audio',
                            rect: ['0', '0', '320px', '45px', 'auto', 'auto'],
                            source: [aud+"Chris_Zabriskie_-_09_-_Cylinder_Nine.mp3"],
                            preload: 'auto'
                        },
                        {
                            id: 'Rectangle',
                            type: 'rect',
                            rect: ['1px', '0px', '1024px', '768px', 'auto', 'auto'],
                            opacity: '1',
                            fill: ["rgba(255,255,255,1.00)"],
                            stroke: [0,"rgba(0,0,0,1)","none"]
                        },
                        {
                            id: 'logo-dwm',
                            type: 'image',
                            rect: ['197px', '156px', '608px', '456px', 'auto', 'auto'],
                            opacity: '0.000000',
                            fill: ["rgba(0,0,0,0)",im+"logo-dwm.png",'0px','0px']
                        },
                        {
                            id: 'potatoe_titre',
                            type: 'image',
                            rect: ['329px', '779px', '367px', '48px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"potatoe_titre.svg",'0px','0px']
                        },
                        {
                            id: 'potato_cercle',
                            type: 'image',
                            rect: ['-354px', '116px', '379px', '425px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"potato_cercle.svg",'0px','0px']
                        },
                        {
                            id: 'potato_tete',
                            type: 'image',
                            rect: ['326px', '116px', '379px', '425px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"potato_tete.svg",'0px','0px']
                        },
                        {
                            id: 'Text2',
                            type: 'text',
                            rect: ['391px', '355px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '1',
                            text: "<p style=\"margin: 0px;\">​Présentent</p>",
                            align: "left",
                            font: ['alice, serif', [50, "px"], "rgba(255,255,255,1.00)", "400", "none", "normal", "break-word", "nowrap"],
                            textStyle: ["", "", "", "", "none"]
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '1024px', '768px', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 334123.469,
                    autoPlay: true,
                    data: [
                        [
                            "eid4",
                            "top",
                            11250,
                            6000,
                            "linear",
                            "${bucheron}",
                            '667px',
                            '-25px'
                        ],
                        [
                            "eid14",
                            "top",
                            17250,
                            4250,
                            "linear",
                            "${bucheron}",
                            '-25px',
                            '-24px'
                        ],
                        [
                            "eid16",
                            "top",
                            21500,
                            3750,
                            "linear",
                            "${bucheron}",
                            '-24px',
                            '454px'
                        ],
                        [
                            "eid19",
                            "top",
                            25250,
                            1000,
                            "linear",
                            "${bucheron}",
                            '454px',
                            '508px'
                        ],
                        [
                            "eid21",
                            "top",
                            26250,
                            4972,
                            "linear",
                            "${bucheron}",
                            '508px',
                            '-71px'
                        ],
                        [
                            "eid24",
                            "top",
                            31222,
                            3028,
                            "linear",
                            "${bucheron}",
                            '-71px',
                            '205px'
                        ],
                        [
                            "eid27",
                            "top",
                            34250,
                            3000,
                            "linear",
                            "${bucheron}",
                            '205px',
                            '485px'
                        ],
                        [
                            "eid30",
                            "top",
                            37250,
                            5000,
                            "linear",
                            "${bucheron}",
                            '485px',
                            '302px'
                        ],
                        [
                            "eid33",
                            "top",
                            42250,
                            3018,
                            "linear",
                            "${bucheron}",
                            '302px',
                            '486px'
                        ],
                        [
                            "eid36",
                            "top",
                            45268,
                            6000,
                            "linear",
                            "${bucheron}",
                            '667px',
                            '-25px'
                        ],
                        [
                            "eid37",
                            "top",
                            51268,
                            4250,
                            "linear",
                            "${bucheron}",
                            '-25px',
                            '-24px'
                        ],
                        [
                            "eid38",
                            "top",
                            55518,
                            3750,
                            "linear",
                            "${bucheron}",
                            '-24px',
                            '454px'
                        ],
                        [
                            "eid39",
                            "top",
                            59268,
                            1000,
                            "linear",
                            "${bucheron}",
                            '454px',
                            '508px'
                        ],
                        [
                            "eid40",
                            "top",
                            60268,
                            4972,
                            "linear",
                            "${bucheron}",
                            '508px',
                            '-71px'
                        ],
                        [
                            "eid41",
                            "top",
                            65240,
                            3028,
                            "linear",
                            "${bucheron}",
                            '-71px',
                            '205px'
                        ],
                        [
                            "eid42",
                            "top",
                            68268,
                            3000,
                            "linear",
                            "${bucheron}",
                            '205px',
                            '485px'
                        ],
                        [
                            "eid43",
                            "top",
                            71268,
                            5000,
                            "linear",
                            "${bucheron}",
                            '485px',
                            '302px'
                        ],
                        [
                            "eid44",
                            "top",
                            76268,
                            3018,
                            "linear",
                            "${bucheron}",
                            '302px',
                            '486px'
                        ],
                        [
                            "eid62",
                            "top",
                            79286,
                            6000,
                            "linear",
                            "${bucheron}",
                            '667px',
                            '-25px'
                        ],
                        [
                            "eid63",
                            "top",
                            85286,
                            4250,
                            "linear",
                            "${bucheron}",
                            '-25px',
                            '-24px'
                        ],
                        [
                            "eid64",
                            "top",
                            89536,
                            3750,
                            "linear",
                            "${bucheron}",
                            '-24px',
                            '454px'
                        ],
                        [
                            "eid65",
                            "top",
                            93286,
                            1000,
                            "linear",
                            "${bucheron}",
                            '454px',
                            '508px'
                        ],
                        [
                            "eid66",
                            "top",
                            94286,
                            4972,
                            "linear",
                            "${bucheron}",
                            '508px',
                            '-71px'
                        ],
                        [
                            "eid67",
                            "top",
                            99258,
                            3028,
                            "linear",
                            "${bucheron}",
                            '-71px',
                            '205px'
                        ],
                        [
                            "eid68",
                            "top",
                            102286,
                            3000,
                            "linear",
                            "${bucheron}",
                            '205px',
                            '485px'
                        ],
                        [
                            "eid69",
                            "top",
                            105286,
                            5000,
                            "linear",
                            "${bucheron}",
                            '485px',
                            '302px'
                        ],
                        [
                            "eid70",
                            "top",
                            110286,
                            3018,
                            "linear",
                            "${bucheron}",
                            '302px',
                            '486px'
                        ],
                        [
                            "eid71",
                            "top",
                            113304,
                            6000,
                            "linear",
                            "${bucheron}",
                            '667px',
                            '-25px'
                        ],
                        [
                            "eid72",
                            "top",
                            119304,
                            4250,
                            "linear",
                            "${bucheron}",
                            '-25px',
                            '-24px'
                        ],
                        [
                            "eid73",
                            "top",
                            123554,
                            3750,
                            "linear",
                            "${bucheron}",
                            '-24px',
                            '454px'
                        ],
                        [
                            "eid74",
                            "top",
                            127304,
                            1000,
                            "linear",
                            "${bucheron}",
                            '454px',
                            '508px'
                        ],
                        [
                            "eid75",
                            "top",
                            128304,
                            4972,
                            "linear",
                            "${bucheron}",
                            '508px',
                            '-71px'
                        ],
                        [
                            "eid76",
                            "top",
                            133276,
                            3028,
                            "linear",
                            "${bucheron}",
                            '-71px',
                            '205px'
                        ],
                        [
                            "eid77",
                            "top",
                            136304,
                            3000,
                            "linear",
                            "${bucheron}",
                            '205px',
                            '485px'
                        ],
                        [
                            "eid78",
                            "top",
                            139304,
                            5000,
                            "linear",
                            "${bucheron}",
                            '485px',
                            '302px'
                        ],
                        [
                            "eid79",
                            "top",
                            144304,
                            3018,
                            "linear",
                            "${bucheron}",
                            '302px',
                            '486px'
                        ],
                        [
                            "eid168",
                            "top",
                            147322,
                            6000,
                            "linear",
                            "${bucheron}",
                            '667px',
                            '-25px'
                        ],
                        [
                            "eid169",
                            "top",
                            153322,
                            4250,
                            "linear",
                            "${bucheron}",
                            '-25px',
                            '-24px'
                        ],
                        [
                            "eid170",
                            "top",
                            157572,
                            3750,
                            "linear",
                            "${bucheron}",
                            '-24px',
                            '454px'
                        ],
                        [
                            "eid171",
                            "top",
                            161322,
                            1000,
                            "linear",
                            "${bucheron}",
                            '454px',
                            '508px'
                        ],
                        [
                            "eid172",
                            "top",
                            162322,
                            4972,
                            "linear",
                            "${bucheron}",
                            '508px',
                            '-71px'
                        ],
                        [
                            "eid173",
                            "top",
                            167294,
                            3028,
                            "linear",
                            "${bucheron}",
                            '-71px',
                            '205px'
                        ],
                        [
                            "eid174",
                            "top",
                            170322,
                            3000,
                            "linear",
                            "${bucheron}",
                            '205px',
                            '485px'
                        ],
                        [
                            "eid175",
                            "top",
                            173322,
                            5000,
                            "linear",
                            "${bucheron}",
                            '485px',
                            '302px'
                        ],
                        [
                            "eid176",
                            "top",
                            178322,
                            3018,
                            "linear",
                            "${bucheron}",
                            '302px',
                            '486px'
                        ],
                        [
                            "eid177",
                            "top",
                            181340,
                            6000,
                            "linear",
                            "${bucheron}",
                            '667px',
                            '-25px'
                        ],
                        [
                            "eid178",
                            "top",
                            187340,
                            4250,
                            "linear",
                            "${bucheron}",
                            '-25px',
                            '-24px'
                        ],
                        [
                            "eid179",
                            "top",
                            191590,
                            3750,
                            "linear",
                            "${bucheron}",
                            '-24px',
                            '454px'
                        ],
                        [
                            "eid180",
                            "top",
                            195340,
                            1000,
                            "linear",
                            "${bucheron}",
                            '454px',
                            '508px'
                        ],
                        [
                            "eid181",
                            "top",
                            196340,
                            4972,
                            "linear",
                            "${bucheron}",
                            '508px',
                            '-71px'
                        ],
                        [
                            "eid182",
                            "top",
                            201312,
                            3028,
                            "linear",
                            "${bucheron}",
                            '-71px',
                            '205px'
                        ],
                        [
                            "eid183",
                            "top",
                            204340,
                            3000,
                            "linear",
                            "${bucheron}",
                            '205px',
                            '485px'
                        ],
                        [
                            "eid184",
                            "top",
                            207340,
                            5000,
                            "linear",
                            "${bucheron}",
                            '485px',
                            '302px'
                        ],
                        [
                            "eid185",
                            "top",
                            212340,
                            3018,
                            "linear",
                            "${bucheron}",
                            '302px',
                            '486px'
                        ],
                        [
                            "eid186",
                            "top",
                            215358,
                            6000,
                            "linear",
                            "${bucheron}",
                            '667px',
                            '-25px'
                        ],
                        [
                            "eid187",
                            "top",
                            221358,
                            4250,
                            "linear",
                            "${bucheron}",
                            '-25px',
                            '-24px'
                        ],
                        [
                            "eid188",
                            "top",
                            225608,
                            3750,
                            "linear",
                            "${bucheron}",
                            '-24px',
                            '454px'
                        ],
                        [
                            "eid189",
                            "top",
                            229358,
                            1000,
                            "linear",
                            "${bucheron}",
                            '454px',
                            '508px'
                        ],
                        [
                            "eid190",
                            "top",
                            230358,
                            4972,
                            "linear",
                            "${bucheron}",
                            '508px',
                            '-71px'
                        ],
                        [
                            "eid191",
                            "top",
                            235330,
                            3028,
                            "linear",
                            "${bucheron}",
                            '-71px',
                            '205px'
                        ],
                        [
                            "eid192",
                            "top",
                            238358,
                            3000,
                            "linear",
                            "${bucheron}",
                            '205px',
                            '485px'
                        ],
                        [
                            "eid193",
                            "top",
                            241358,
                            5000,
                            "linear",
                            "${bucheron}",
                            '485px',
                            '302px'
                        ],
                        [
                            "eid194",
                            "top",
                            246358,
                            3018,
                            "linear",
                            "${bucheron}",
                            '302px',
                            '486px'
                        ],
                        [
                            "eid195",
                            "top",
                            249376,
                            6000,
                            "linear",
                            "${bucheron}",
                            '667px',
                            '-25px'
                        ],
                        [
                            "eid196",
                            "top",
                            255376,
                            4250,
                            "linear",
                            "${bucheron}",
                            '-25px',
                            '-24px'
                        ],
                        [
                            "eid197",
                            "top",
                            259626,
                            3750,
                            "linear",
                            "${bucheron}",
                            '-24px',
                            '454px'
                        ],
                        [
                            "eid198",
                            "top",
                            263376,
                            1000,
                            "linear",
                            "${bucheron}",
                            '454px',
                            '508px'
                        ],
                        [
                            "eid199",
                            "top",
                            264376,
                            4972,
                            "linear",
                            "${bucheron}",
                            '508px',
                            '-71px'
                        ],
                        [
                            "eid200",
                            "top",
                            269348,
                            3028,
                            "linear",
                            "${bucheron}",
                            '-71px',
                            '205px'
                        ],
                        [
                            "eid201",
                            "top",
                            272376,
                            3000,
                            "linear",
                            "${bucheron}",
                            '205px',
                            '485px'
                        ],
                        [
                            "eid202",
                            "top",
                            275376,
                            5000,
                            "linear",
                            "${bucheron}",
                            '485px',
                            '302px'
                        ],
                        [
                            "eid203",
                            "top",
                            280376,
                            3018,
                            "linear",
                            "${bucheron}",
                            '302px',
                            '486px'
                        ],
                        [
                            "eid690",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${Rectangle}",
                            '1',
                            '1'
                        ],
                        [
                            "eid746",
                            "opacity",
                            8825,
                            249,
                            "linear",
                            "${Rectangle}",
                            '1',
                            '0'
                        ],
                        [
                            "eid8",
                            "rotateZ",
                            11250,
                            6000,
                            "linear",
                            "${bucheron}",
                            '1deg',
                            '360deg'
                        ],
                        [
                            "eid13",
                            "rotateZ",
                            17250,
                            8000,
                            "linear",
                            "${bucheron}",
                            '360deg',
                            '620deg'
                        ],
                        [
                            "eid20",
                            "rotateZ",
                            25250,
                            1000,
                            "linear",
                            "${bucheron}",
                            '620deg',
                            '650deg'
                        ],
                        [
                            "eid23",
                            "rotateZ",
                            26250,
                            4972,
                            "linear",
                            "${bucheron}",
                            '650deg',
                            '800deg'
                        ],
                        [
                            "eid26",
                            "rotateZ",
                            31222,
                            3028,
                            "linear",
                            "${bucheron}",
                            '800deg',
                            '920deg'
                        ],
                        [
                            "eid29",
                            "rotateZ",
                            34250,
                            3000,
                            "linear",
                            "${bucheron}",
                            '920deg',
                            '1000deg'
                        ],
                        [
                            "eid32",
                            "rotateZ",
                            37250,
                            5000,
                            "linear",
                            "${bucheron}",
                            '1000deg',
                            '1200deg'
                        ],
                        [
                            "eid35",
                            "rotateZ",
                            42250,
                            3018,
                            "linear",
                            "${bucheron}",
                            '1200deg',
                            '1300deg'
                        ],
                        [
                            "eid54",
                            "rotateZ",
                            45268,
                            6000,
                            "linear",
                            "${bucheron}",
                            '1deg',
                            '360deg'
                        ],
                        [
                            "eid55",
                            "rotateZ",
                            51268,
                            8000,
                            "linear",
                            "${bucheron}",
                            '360deg',
                            '620deg'
                        ],
                        [
                            "eid56",
                            "rotateZ",
                            59268,
                            1000,
                            "linear",
                            "${bucheron}",
                            '620deg',
                            '650deg'
                        ],
                        [
                            "eid57",
                            "rotateZ",
                            60268,
                            4972,
                            "linear",
                            "${bucheron}",
                            '650deg',
                            '800deg'
                        ],
                        [
                            "eid58",
                            "rotateZ",
                            65240,
                            3028,
                            "linear",
                            "${bucheron}",
                            '800deg',
                            '920deg'
                        ],
                        [
                            "eid59",
                            "rotateZ",
                            68268,
                            3000,
                            "linear",
                            "${bucheron}",
                            '920deg',
                            '1000deg'
                        ],
                        [
                            "eid60",
                            "rotateZ",
                            71268,
                            5000,
                            "linear",
                            "${bucheron}",
                            '1000deg',
                            '1200deg'
                        ],
                        [
                            "eid61",
                            "rotateZ",
                            76268,
                            3018,
                            "linear",
                            "${bucheron}",
                            '1200deg',
                            '1300deg'
                        ],
                        [
                            "eid98",
                            "rotateZ",
                            79286,
                            6000,
                            "linear",
                            "${bucheron}",
                            '1deg',
                            '360deg'
                        ],
                        [
                            "eid99",
                            "rotateZ",
                            85286,
                            8000,
                            "linear",
                            "${bucheron}",
                            '360deg',
                            '620deg'
                        ],
                        [
                            "eid100",
                            "rotateZ",
                            93286,
                            1000,
                            "linear",
                            "${bucheron}",
                            '620deg',
                            '650deg'
                        ],
                        [
                            "eid101",
                            "rotateZ",
                            94286,
                            4972,
                            "linear",
                            "${bucheron}",
                            '650deg',
                            '800deg'
                        ],
                        [
                            "eid102",
                            "rotateZ",
                            99258,
                            3028,
                            "linear",
                            "${bucheron}",
                            '800deg',
                            '920deg'
                        ],
                        [
                            "eid103",
                            "rotateZ",
                            102286,
                            3000,
                            "linear",
                            "${bucheron}",
                            '920deg',
                            '1000deg'
                        ],
                        [
                            "eid104",
                            "rotateZ",
                            105286,
                            5000,
                            "linear",
                            "${bucheron}",
                            '1000deg',
                            '1200deg'
                        ],
                        [
                            "eid105",
                            "rotateZ",
                            110286,
                            3018,
                            "linear",
                            "${bucheron}",
                            '1200deg',
                            '1300deg'
                        ],
                        [
                            "eid106",
                            "rotateZ",
                            113304,
                            6000,
                            "linear",
                            "${bucheron}",
                            '1deg',
                            '360deg'
                        ],
                        [
                            "eid107",
                            "rotateZ",
                            119304,
                            8000,
                            "linear",
                            "${bucheron}",
                            '360deg',
                            '620deg'
                        ],
                        [
                            "eid108",
                            "rotateZ",
                            127304,
                            1000,
                            "linear",
                            "${bucheron}",
                            '620deg',
                            '650deg'
                        ],
                        [
                            "eid109",
                            "rotateZ",
                            128304,
                            4972,
                            "linear",
                            "${bucheron}",
                            '650deg',
                            '800deg'
                        ],
                        [
                            "eid110",
                            "rotateZ",
                            133276,
                            3028,
                            "linear",
                            "${bucheron}",
                            '800deg',
                            '920deg'
                        ],
                        [
                            "eid111",
                            "rotateZ",
                            136304,
                            3000,
                            "linear",
                            "${bucheron}",
                            '920deg',
                            '1000deg'
                        ],
                        [
                            "eid112",
                            "rotateZ",
                            139304,
                            5000,
                            "linear",
                            "${bucheron}",
                            '1000deg',
                            '1200deg'
                        ],
                        [
                            "eid113",
                            "rotateZ",
                            144304,
                            3018,
                            "linear",
                            "${bucheron}",
                            '1200deg',
                            '1300deg'
                        ],
                        [
                            "eid240",
                            "rotateZ",
                            147322,
                            6000,
                            "linear",
                            "${bucheron}",
                            '1deg',
                            '360deg'
                        ],
                        [
                            "eid241",
                            "rotateZ",
                            153322,
                            8000,
                            "linear",
                            "${bucheron}",
                            '360deg',
                            '620deg'
                        ],
                        [
                            "eid242",
                            "rotateZ",
                            161322,
                            1000,
                            "linear",
                            "${bucheron}",
                            '620deg',
                            '650deg'
                        ],
                        [
                            "eid243",
                            "rotateZ",
                            162322,
                            4972,
                            "linear",
                            "${bucheron}",
                            '650deg',
                            '800deg'
                        ],
                        [
                            "eid244",
                            "rotateZ",
                            167294,
                            3028,
                            "linear",
                            "${bucheron}",
                            '800deg',
                            '920deg'
                        ],
                        [
                            "eid245",
                            "rotateZ",
                            170322,
                            3000,
                            "linear",
                            "${bucheron}",
                            '920deg',
                            '1000deg'
                        ],
                        [
                            "eid246",
                            "rotateZ",
                            173322,
                            5000,
                            "linear",
                            "${bucheron}",
                            '1000deg',
                            '1200deg'
                        ],
                        [
                            "eid247",
                            "rotateZ",
                            178322,
                            3018,
                            "linear",
                            "${bucheron}",
                            '1200deg',
                            '1300deg'
                        ],
                        [
                            "eid248",
                            "rotateZ",
                            181340,
                            6000,
                            "linear",
                            "${bucheron}",
                            '1deg',
                            '360deg'
                        ],
                        [
                            "eid249",
                            "rotateZ",
                            187340,
                            8000,
                            "linear",
                            "${bucheron}",
                            '360deg',
                            '620deg'
                        ],
                        [
                            "eid250",
                            "rotateZ",
                            195340,
                            1000,
                            "linear",
                            "${bucheron}",
                            '620deg',
                            '650deg'
                        ],
                        [
                            "eid251",
                            "rotateZ",
                            196340,
                            4972,
                            "linear",
                            "${bucheron}",
                            '650deg',
                            '800deg'
                        ],
                        [
                            "eid252",
                            "rotateZ",
                            201312,
                            3028,
                            "linear",
                            "${bucheron}",
                            '800deg',
                            '920deg'
                        ],
                        [
                            "eid253",
                            "rotateZ",
                            204340,
                            3000,
                            "linear",
                            "${bucheron}",
                            '920deg',
                            '1000deg'
                        ],
                        [
                            "eid254",
                            "rotateZ",
                            207340,
                            5000,
                            "linear",
                            "${bucheron}",
                            '1000deg',
                            '1200deg'
                        ],
                        [
                            "eid255",
                            "rotateZ",
                            212340,
                            3018,
                            "linear",
                            "${bucheron}",
                            '1200deg',
                            '1300deg'
                        ],
                        [
                            "eid256",
                            "rotateZ",
                            215358,
                            6000,
                            "linear",
                            "${bucheron}",
                            '1deg',
                            '360deg'
                        ],
                        [
                            "eid257",
                            "rotateZ",
                            221358,
                            8000,
                            "linear",
                            "${bucheron}",
                            '360deg',
                            '620deg'
                        ],
                        [
                            "eid258",
                            "rotateZ",
                            229358,
                            1000,
                            "linear",
                            "${bucheron}",
                            '620deg',
                            '650deg'
                        ],
                        [
                            "eid259",
                            "rotateZ",
                            230358,
                            4972,
                            "linear",
                            "${bucheron}",
                            '650deg',
                            '800deg'
                        ],
                        [
                            "eid260",
                            "rotateZ",
                            235330,
                            3028,
                            "linear",
                            "${bucheron}",
                            '800deg',
                            '920deg'
                        ],
                        [
                            "eid261",
                            "rotateZ",
                            238358,
                            3000,
                            "linear",
                            "${bucheron}",
                            '920deg',
                            '1000deg'
                        ],
                        [
                            "eid262",
                            "rotateZ",
                            241358,
                            5000,
                            "linear",
                            "${bucheron}",
                            '1000deg',
                            '1200deg'
                        ],
                        [
                            "eid263",
                            "rotateZ",
                            246358,
                            3018,
                            "linear",
                            "${bucheron}",
                            '1200deg',
                            '1300deg'
                        ],
                        [
                            "eid264",
                            "rotateZ",
                            249376,
                            6000,
                            "linear",
                            "${bucheron}",
                            '1deg',
                            '360deg'
                        ],
                        [
                            "eid265",
                            "rotateZ",
                            255376,
                            8000,
                            "linear",
                            "${bucheron}",
                            '360deg',
                            '620deg'
                        ],
                        [
                            "eid266",
                            "rotateZ",
                            263376,
                            1000,
                            "linear",
                            "${bucheron}",
                            '620deg',
                            '650deg'
                        ],
                        [
                            "eid267",
                            "rotateZ",
                            264376,
                            4972,
                            "linear",
                            "${bucheron}",
                            '650deg',
                            '800deg'
                        ],
                        [
                            "eid268",
                            "rotateZ",
                            269348,
                            3028,
                            "linear",
                            "${bucheron}",
                            '800deg',
                            '920deg'
                        ],
                        [
                            "eid269",
                            "rotateZ",
                            272376,
                            3000,
                            "linear",
                            "${bucheron}",
                            '920deg',
                            '1000deg'
                        ],
                        [
                            "eid270",
                            "rotateZ",
                            275376,
                            5000,
                            "linear",
                            "${bucheron}",
                            '1000deg',
                            '1200deg'
                        ],
                        [
                            "eid271",
                            "rotateZ",
                            280376,
                            3018,
                            "linear",
                            "${bucheron}",
                            '1200deg',
                            '1300deg'
                        ],
                        [
                            "eid5",
                            "left",
                            11250,
                            6000,
                            "linear",
                            "${bucheron}",
                            '-249px',
                            '776px'
                        ],
                        [
                            "eid11",
                            "left",
                            17250,
                            4250,
                            "linear",
                            "${bucheron}",
                            '776px',
                            '274px'
                        ],
                        [
                            "eid17",
                            "left",
                            21500,
                            3750,
                            "linear",
                            "${bucheron}",
                            '274px',
                            '-23px'
                        ],
                        [
                            "eid18",
                            "left",
                            25250,
                            1000,
                            "linear",
                            "${bucheron}",
                            '-23px',
                            '13px'
                        ],
                        [
                            "eid22",
                            "left",
                            26250,
                            4972,
                            "linear",
                            "${bucheron}",
                            '13px',
                            '447px'
                        ],
                        [
                            "eid25",
                            "left",
                            31222,
                            3028,
                            "linear",
                            "${bucheron}",
                            '447px',
                            '752px'
                        ],
                        [
                            "eid28",
                            "left",
                            34250,
                            3000,
                            "linear",
                            "${bucheron}",
                            '752px',
                            '659px'
                        ],
                        [
                            "eid31",
                            "left",
                            37250,
                            5000,
                            "linear",
                            "${bucheron}",
                            '659px',
                            '-16px'
                        ],
                        [
                            "eid34",
                            "left",
                            42250,
                            3018,
                            "linear",
                            "${bucheron}",
                            '-16px',
                            '-46px'
                        ],
                        [
                            "eid45",
                            "left",
                            45268,
                            6000,
                            "linear",
                            "${bucheron}",
                            '-249px',
                            '776px'
                        ],
                        [
                            "eid46",
                            "left",
                            51268,
                            4250,
                            "linear",
                            "${bucheron}",
                            '776px',
                            '274px'
                        ],
                        [
                            "eid47",
                            "left",
                            55518,
                            3750,
                            "linear",
                            "${bucheron}",
                            '274px',
                            '-23px'
                        ],
                        [
                            "eid48",
                            "left",
                            59268,
                            1000,
                            "linear",
                            "${bucheron}",
                            '-23px',
                            '13px'
                        ],
                        [
                            "eid49",
                            "left",
                            60268,
                            4972,
                            "linear",
                            "${bucheron}",
                            '13px',
                            '447px'
                        ],
                        [
                            "eid50",
                            "left",
                            65240,
                            3028,
                            "linear",
                            "${bucheron}",
                            '447px',
                            '752px'
                        ],
                        [
                            "eid51",
                            "left",
                            68268,
                            3000,
                            "linear",
                            "${bucheron}",
                            '752px',
                            '659px'
                        ],
                        [
                            "eid52",
                            "left",
                            71268,
                            5000,
                            "linear",
                            "${bucheron}",
                            '659px',
                            '-16px'
                        ],
                        [
                            "eid53",
                            "left",
                            76268,
                            3018,
                            "linear",
                            "${bucheron}",
                            '-16px',
                            '-46px'
                        ],
                        [
                            "eid80",
                            "left",
                            79286,
                            6000,
                            "linear",
                            "${bucheron}",
                            '-249px',
                            '776px'
                        ],
                        [
                            "eid81",
                            "left",
                            85286,
                            4250,
                            "linear",
                            "${bucheron}",
                            '776px',
                            '274px'
                        ],
                        [
                            "eid82",
                            "left",
                            89536,
                            3750,
                            "linear",
                            "${bucheron}",
                            '274px',
                            '-23px'
                        ],
                        [
                            "eid83",
                            "left",
                            93286,
                            1000,
                            "linear",
                            "${bucheron}",
                            '-23px',
                            '13px'
                        ],
                        [
                            "eid84",
                            "left",
                            94286,
                            4972,
                            "linear",
                            "${bucheron}",
                            '13px',
                            '447px'
                        ],
                        [
                            "eid85",
                            "left",
                            99258,
                            3028,
                            "linear",
                            "${bucheron}",
                            '447px',
                            '752px'
                        ],
                        [
                            "eid86",
                            "left",
                            102286,
                            3000,
                            "linear",
                            "${bucheron}",
                            '752px',
                            '659px'
                        ],
                        [
                            "eid87",
                            "left",
                            105286,
                            5000,
                            "linear",
                            "${bucheron}",
                            '659px',
                            '-16px'
                        ],
                        [
                            "eid88",
                            "left",
                            110286,
                            3018,
                            "linear",
                            "${bucheron}",
                            '-16px',
                            '-46px'
                        ],
                        [
                            "eid89",
                            "left",
                            113304,
                            6000,
                            "linear",
                            "${bucheron}",
                            '-249px',
                            '776px'
                        ],
                        [
                            "eid90",
                            "left",
                            119304,
                            4250,
                            "linear",
                            "${bucheron}",
                            '776px',
                            '274px'
                        ],
                        [
                            "eid91",
                            "left",
                            123554,
                            3750,
                            "linear",
                            "${bucheron}",
                            '274px',
                            '-23px'
                        ],
                        [
                            "eid92",
                            "left",
                            127304,
                            1000,
                            "linear",
                            "${bucheron}",
                            '-23px',
                            '13px'
                        ],
                        [
                            "eid93",
                            "left",
                            128304,
                            4972,
                            "linear",
                            "${bucheron}",
                            '13px',
                            '447px'
                        ],
                        [
                            "eid94",
                            "left",
                            133276,
                            3028,
                            "linear",
                            "${bucheron}",
                            '447px',
                            '752px'
                        ],
                        [
                            "eid95",
                            "left",
                            136304,
                            3000,
                            "linear",
                            "${bucheron}",
                            '752px',
                            '659px'
                        ],
                        [
                            "eid96",
                            "left",
                            139304,
                            5000,
                            "linear",
                            "${bucheron}",
                            '659px',
                            '-16px'
                        ],
                        [
                            "eid97",
                            "left",
                            144304,
                            3018,
                            "linear",
                            "${bucheron}",
                            '-16px',
                            '-46px'
                        ],
                        [
                            "eid204",
                            "left",
                            147322,
                            6000,
                            "linear",
                            "${bucheron}",
                            '-249px',
                            '776px'
                        ],
                        [
                            "eid205",
                            "left",
                            153322,
                            4250,
                            "linear",
                            "${bucheron}",
                            '776px',
                            '274px'
                        ],
                        [
                            "eid206",
                            "left",
                            157572,
                            3750,
                            "linear",
                            "${bucheron}",
                            '274px',
                            '-23px'
                        ],
                        [
                            "eid207",
                            "left",
                            161322,
                            1000,
                            "linear",
                            "${bucheron}",
                            '-23px',
                            '13px'
                        ],
                        [
                            "eid208",
                            "left",
                            162322,
                            4972,
                            "linear",
                            "${bucheron}",
                            '13px',
                            '447px'
                        ],
                        [
                            "eid209",
                            "left",
                            167294,
                            3028,
                            "linear",
                            "${bucheron}",
                            '447px',
                            '752px'
                        ],
                        [
                            "eid210",
                            "left",
                            170322,
                            3000,
                            "linear",
                            "${bucheron}",
                            '752px',
                            '659px'
                        ],
                        [
                            "eid211",
                            "left",
                            173322,
                            5000,
                            "linear",
                            "${bucheron}",
                            '659px',
                            '-16px'
                        ],
                        [
                            "eid212",
                            "left",
                            178322,
                            3018,
                            "linear",
                            "${bucheron}",
                            '-16px',
                            '-46px'
                        ],
                        [
                            "eid213",
                            "left",
                            181340,
                            6000,
                            "linear",
                            "${bucheron}",
                            '-249px',
                            '776px'
                        ],
                        [
                            "eid214",
                            "left",
                            187340,
                            4250,
                            "linear",
                            "${bucheron}",
                            '776px',
                            '274px'
                        ],
                        [
                            "eid215",
                            "left",
                            191590,
                            3750,
                            "linear",
                            "${bucheron}",
                            '274px',
                            '-23px'
                        ],
                        [
                            "eid216",
                            "left",
                            195340,
                            1000,
                            "linear",
                            "${bucheron}",
                            '-23px',
                            '13px'
                        ],
                        [
                            "eid217",
                            "left",
                            196340,
                            4972,
                            "linear",
                            "${bucheron}",
                            '13px',
                            '447px'
                        ],
                        [
                            "eid218",
                            "left",
                            201312,
                            3028,
                            "linear",
                            "${bucheron}",
                            '447px',
                            '752px'
                        ],
                        [
                            "eid219",
                            "left",
                            204340,
                            3000,
                            "linear",
                            "${bucheron}",
                            '752px',
                            '659px'
                        ],
                        [
                            "eid220",
                            "left",
                            207340,
                            5000,
                            "linear",
                            "${bucheron}",
                            '659px',
                            '-16px'
                        ],
                        [
                            "eid221",
                            "left",
                            212340,
                            3018,
                            "linear",
                            "${bucheron}",
                            '-16px',
                            '-46px'
                        ],
                        [
                            "eid222",
                            "left",
                            215358,
                            6000,
                            "linear",
                            "${bucheron}",
                            '-249px',
                            '776px'
                        ],
                        [
                            "eid223",
                            "left",
                            221358,
                            4250,
                            "linear",
                            "${bucheron}",
                            '776px',
                            '274px'
                        ],
                        [
                            "eid224",
                            "left",
                            225608,
                            3750,
                            "linear",
                            "${bucheron}",
                            '274px',
                            '-23px'
                        ],
                        [
                            "eid225",
                            "left",
                            229358,
                            1000,
                            "linear",
                            "${bucheron}",
                            '-23px',
                            '13px'
                        ],
                        [
                            "eid226",
                            "left",
                            230358,
                            4972,
                            "linear",
                            "${bucheron}",
                            '13px',
                            '447px'
                        ],
                        [
                            "eid227",
                            "left",
                            235330,
                            3028,
                            "linear",
                            "${bucheron}",
                            '447px',
                            '752px'
                        ],
                        [
                            "eid228",
                            "left",
                            238358,
                            3000,
                            "linear",
                            "${bucheron}",
                            '752px',
                            '659px'
                        ],
                        [
                            "eid229",
                            "left",
                            241358,
                            5000,
                            "linear",
                            "${bucheron}",
                            '659px',
                            '-16px'
                        ],
                        [
                            "eid230",
                            "left",
                            246358,
                            3018,
                            "linear",
                            "${bucheron}",
                            '-16px',
                            '-46px'
                        ],
                        [
                            "eid231",
                            "left",
                            249376,
                            6000,
                            "linear",
                            "${bucheron}",
                            '-249px',
                            '776px'
                        ],
                        [
                            "eid232",
                            "left",
                            255376,
                            4250,
                            "linear",
                            "${bucheron}",
                            '776px',
                            '274px'
                        ],
                        [
                            "eid233",
                            "left",
                            259626,
                            3750,
                            "linear",
                            "${bucheron}",
                            '274px',
                            '-23px'
                        ],
                        [
                            "eid234",
                            "left",
                            263376,
                            1000,
                            "linear",
                            "${bucheron}",
                            '-23px',
                            '13px'
                        ],
                        [
                            "eid235",
                            "left",
                            264376,
                            4972,
                            "linear",
                            "${bucheron}",
                            '13px',
                            '447px'
                        ],
                        [
                            "eid236",
                            "left",
                            269348,
                            3028,
                            "linear",
                            "${bucheron}",
                            '447px',
                            '752px'
                        ],
                        [
                            "eid237",
                            "left",
                            272376,
                            3000,
                            "linear",
                            "${bucheron}",
                            '752px',
                            '659px'
                        ],
                        [
                            "eid238",
                            "left",
                            275376,
                            5000,
                            "linear",
                            "${bucheron}",
                            '659px',
                            '-16px'
                        ],
                        [
                            "eid239",
                            "left",
                            280376,
                            3018,
                            "linear",
                            "${bucheron}",
                            '-16px',
                            '-46px'
                        ],
                        [
                            "eid705",
                            "left",
                            5252,
                            0,
                            "linear",
                            "${potatoe_titre}",
                            '329px',
                            '329px'
                        ],
                        [
                            "eid737",
                            "left",
                            8704,
                            0,
                            "easeOutQuad",
                            "${potatoe_titre}",
                            '329px',
                            '330px'
                        ],
                        [
                            "eid750",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${logo-dwm}",
                            '0.000000',
                            '0.000000'
                        ],
                        [
                            "eid693",
                            "opacity",
                            1250,
                            1000,
                            "linear",
                            "${logo-dwm}",
                            '0.000000',
                            '1'
                        ],
                        [
                            "eid696",
                            "opacity",
                            3454,
                            796,
                            "linear",
                            "${logo-dwm}",
                            '1',
                            '0'
                        ],
                        [
                            "eid707",
                            "top",
                            4057,
                            0,
                            "linear",
                            "${potato_tete}",
                            '116px',
                            '116px'
                        ],
                        [
                            "eid697",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${potatoe_titre}",
                            '0',
                            '0'
                        ],
                        [
                            "eid721",
                            "opacity",
                            4057,
                            1195,
                            "easeInQuad",
                            "${potatoe_titre}",
                            '0',
                            '1'
                        ],
                        [
                            "eid730",
                            "opacity",
                            7750,
                            954,
                            "easeOutQuad",
                            "${potatoe_titre}",
                            '1',
                            '0'
                        ],
                        [
                            "eid716",
                            "top",
                            4057,
                            1195,
                            "easeInQuad",
                            "${potatoe_titre}",
                            '779px',
                            '493px'
                        ],
                        [
                            "eid699",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${potato_cercle}",
                            '0',
                            '0'
                        ],
                        [
                            "eid720",
                            "opacity",
                            4057,
                            1195,
                            "easeInQuad",
                            "${potato_cercle}",
                            '0',
                            '1'
                        ],
                        [
                            "eid729",
                            "opacity",
                            7750,
                            954,
                            "easeOutQuad",
                            "${potato_cercle}",
                            '1',
                            '0'
                        ],
                        [
                            "eid719",
                            "opacity",
                            0,
                            0,
                            "easeInQuad",
                            "${potato_tete}",
                            '0',
                            '0'
                        ],
                        [
                            "eid718",
                            "opacity",
                            4057,
                            1195,
                            "easeInQuad",
                            "${potato_tete}",
                            '0',
                            '1'
                        ],
                        [
                            "eid728",
                            "opacity",
                            7750,
                            954,
                            "easeOutQuad",
                            "${potato_tete}",
                            '1',
                            '0'
                        ],
                        [
                            "eid751",
                            "color",
                            9500,
                            0,
                            "linear",
                            "${Text2}",
                            'rgba(255,255,255,1.00)',
                            'rgba(255,255,255,1.00)'
                        ],
                        [
                            "eid711",
                            "left",
                            3250,
                            807,
                            "easeOutQuad",
                            "${potato_tete}",
                            '1019px',
                            '311px'
                        ],
                        [
                            "eid748",
                            "left",
                            4057,
                            1195,
                            "easeInQuad",
                            "${potato_tete}",
                            '1031px',
                            '311px'
                        ],
                        [
                            "eid747",
                            "left",
                            5252,
                            0,
                            "linear",
                            "${potato_tete}",
                            '311px',
                            '313px'
                        ],
                        [
                            "eid706",
                            "top",
                            4057,
                            0,
                            "linear",
                            "${potato_cercle}",
                            '116px',
                            '116px'
                        ],
                        [
                            "eid714",
                            "left",
                            4057,
                            1195,
                            "easeInQuad",
                            "${potato_cercle}",
                            '-354px',
                            '311px'
                        ],
                        [
                            "eid738",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${Text2}",
                            '0',
                            '0'
                        ],
                        [
                            "eid741",
                            "opacity",
                            9310,
                            296,
                            "linear",
                            "${Text2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid744",
                            "opacity",
                            11106,
                            171,
                            "linear",
                            "${Text2}",
                            '1',
                            '0'
                        ],
                            [ "eid167", "trigger", 11250, function executeMediaFunction(e, data) { this._executeMediaAction(e, data); }, ['play', '${Chris_Zabriskie_-_09_-_Cylinder_Nine2}', [] ] ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("ecran_accueil_edgeActions.js");
})("EDGE-5927819");
